name: Update Release Version

on:
  release:
    types: [created]

jobs:
  update_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Release Version
      id: version_check
      run: |
        if [[ "$RELEASE_VERSION" == "0.3" ]]; then
          echo "::set-output name=update_version::true"
        else
          echo "::set-output name=update_version::false"
        fi
      env:
        RELEASE_VERSION: ${{ github.event.release.tag_name }}

    - name: Update Version if Necessary
      if: steps.version_check.outputs.update_version == 'true'
      run: |
        sed -i 's/0.3/0.2/g' version.txt  # Example command to update version in a file
        git commit -am "Update release version to 0.2"
        git push

    # Optionally, you can add steps to create a new release with the updated version.
    - name: Create New Release
      if: steps.version_check.outputs.update_version == 'true'
      run: |
        git tag -a v0.2 -m "Release version 0.2"
        git push origin v0.2 
        
      
        # You can add additional steps here to create a GitHub release with the updated version.
        