name: Update Release Version 0.2

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  update_release:
    name: Update Release Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Release Version
        id: check_release_version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Update Release Version if necessary
        if: steps.check_release_version.outputs.version != 'v0.2'
        run: |
          updated_version="v0.2"
          echo "Updating release version to $updated_version"
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" \
            -d "{\"tag_name\": \"$updated_version\"}"

     
     
