name: Update Release Version roll back

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
    - '*'


jobs:
  update_release:
    name: Update Release Version
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set Release Version Environment Variable
          run: echo "version=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
  
        - name: Update Release Version if necessary
          if: steps.check_release_version.outputs.version != 'v0.2'
          run: |
            updated_version="v0.2"
            echo "Updating release version to $updated_version"
            release_id=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq -r '.id')
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/$release_id" \
              -d "{\"tag_name\": \"$updated_version\"}"
        
  
