name: Rollback Trigger

on:
  push:
    branches:
      - main

jobs:
  detect_rollback:
    name: Detect Rollback
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - run: chmod +x detect.sh

      - name: Run rollback detection script
        run: ./detect.sh
