name: Publish

on:
  release:
    types: [rollback]

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Check Rollback Version
        id: check_rollback_version
        run: echo "Rolled back version is $(echo ${GITHUB_REF#refs/tags/})"

      - name: Trigger Workflow if Rollback Version is not v0.2
        if: steps.check_rollback_version.outputs.rollback_version != 'v0.2'
        run: echo "Workflow triggered because rolled back version is not v0.2"
        # Add your workflow steps here
