name: Update Release Version

on:
  pull_request:
    paths:
      - 'refs/tags/*'

jobs:
  update_release:
    name: Update Release Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history so we can detect tag changes

      - name: Check if Tag Changed
        id: tag_changed
        run: |
          # Check if the tag has changed in the latest commit
          if git diff HEAD^ HEAD --quiet -- refs/tags/; then
            echo "Tag has not changed"
            echo "::set-output name=tag_changed::false"
          else
            echo "Tag has changed"
            echo "::set-output name=tag_changed::true"
          fi

      - name: Check Tag Version
        if: steps.tag_changed.outputs.tag_changed == 'true'
        id: check_tag_version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Update Release Version if necessary
        if: steps.check_tag_version.outputs.version != 'v0.2'
        run: |
          updated_version="v0.2"
          echo "Updating release version to $updated_version"
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.id')
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$release_id" \
            -d "{\"tag_name\": \"$updated_version\"}"
