name: Publish

on:
  release:
    types: [rollback]

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Check Rollback Version
        id: check_rollback_version
        run: echo "Rolled back version is $(echo ${GITHUB_REF#refs/tags/})"

      - name: Trigger Workflow if Rollback Version is not v0.2
        if: steps.check_rollback_version.outputs.rollback_version != 'v0.2'
        run: echo "Workflow triggered because rolled back version is not v0.2"
        
      - name: Update Release Version if necessary
        if: steps.check_release_version.outputs.version != 'v0.2'
        run: |
          updated_version="v0.2"
          echo "Updating release version to $updated_version"
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq -r '.id')
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/$release_id" \
            -d "{\"tag_name\": \"$updated_version\"}"# Add your workflow steps here
