name: Rollback Release Version

on:
  release:
    types:
      - deleted
  workflow_dispatch:

jobs:
  rollback_release:
    name: Rollback Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check New Tag Version
        id: check_new_tag_version
        run: echo "::set-output name=new_tag_version::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Check Previous Tags
        id: check_previous_tags
        run: |
          git fetch --tags
          previous_tags=$(git tag -l)
          echo "::set-output name=previous_tags::$previous_tags"

      - name: Check if Tag Rollback is Needed
        id: check_rollback_needed
        run: |
          if echo "${{ steps.check_previous_tags.outputs.previous_tags }}" | grep -q "${{ steps.check_new_tag_version.outputs.new_tag_version }}"; then
            echo "Rollback needed"
            echo "::set-output name=rollback_needed::true"
          else
            echo "No rollback needed"
            echo "::set-output name=rollback_needed::false"
          fi

      - name: Rollback Release if necessary
        if: steps.check_rollback_needed.outputs.rollback_needed == 'true'
        uses: author/action-rollback@stable
        with:
          tag: ${{ steps.check_new_tag_version.outputs.new_tag_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
