name: Update Version on Release

on:
  release:
    types: [published]

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install bump2version

      - name: Update version
        run: |
          # Assuming your version is stored in a file called VERSION
          CURRENT_VERSION=$(cat VERSION)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F "." '{print $1 "." $2+1}')

          # Updating the version in the VERSION file
          echo $NEW_VERSION > VERSION

          # Committing the changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version to $NEW_VERSION [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
